<?php
/**
 * @file
 * Create/delete 'variable' table values as well as create any database tables.
 */


/**
 * Implements hook_install().
 */
function ch_xml_gateway_install() {
  variable_set('ch_xml_gateway_user', 'XMLGatewayTestUserID');
  variable_set('ch_xml_gateway_pass', 'XMLGatewayTestPassword');
  variable_set('ch_xml_gateway_sender', '');
  variable_set('ch_xml_gateway_CompanyDetails_GiveMortTotals', '0');
  variable_set('ch_xml_gateway_CompanyAppointments_IncludeResignedInd', '0');
  variable_set('ch_xml_gateway_OfficerSearch_OfficerType', 'CUR');
  variable_set('ch_xml_gateway_OfficerSearch_IncludeResignedInd', '0');
  variable_set('ch_xml_gateway_form_settings_OfficerSearch_form_instructions', 'Enter the first name and surname of a company director or secretary.');
  variable_set('ch_xml_gateway_form_settings_OfficerSearch_single_name_input', '1');
  variable_set('ch_xml_gateway_form_settings_OfficerSearch_show_all_forename', '1');
  variable_set('ch_xml_gateway_form_settings_OfficerSearch_show_town', '0');
  variable_set('ch_xml_gateway_form_settings_OfficerSearch_show_officer_type', '0');
  variable_set('ch_xml_gateway_form_settings_OfficerSearch_show_include_resigned', '0');
  variable_set('ch_xml_gateway_form_settings_all_ajax_searches', '1');
}


/**
 * Implements hook_uninstall().
 */
function ch_xml_gateway_uninstall() {
  variable_del('ch_xml_gateway_user');
  variable_del('ch_xml_gateway_pass');
  variable_del('ch_xml_gateway_sender');
  variable_del('ch_xml_gateway_CompanyDetails_GiveMortTotals');
  variable_del('ch_xml_gateway_CompanyAppointments_IncludeResignedInd', '0');
  variable_del('ch_xml_gateway_OfficerSearch_OfficerType');
  variable_del('ch_xml_gateway_OfficerSearch_IncludeResignedInd');
  variable_del('ch_xml_gateway_form_settings_OfficerSearch_form_instructions');
  variable_del('ch_xml_gateway_form_settings_OfficerSearch_single_name_input');
  variable_del('ch_xml_gateway_form_settings_OfficerSearch_show_all_forename');
  variable_del('ch_xml_gateway_form_settings_OfficerSearch_show_town');
  variable_del('ch_xml_gateway_form_settings_OfficerSearch_show_officer_type');
  variable_del('ch_xml_gateway_form_settings_OfficerSearch_show_include_resigned');
  variable_del('ch_xml_gateway_form_settings_all_ajax_searches');
}


/**
 * Implements hook_schema().
 */
function ch_xml_gateway_schema() {
  $schema['ch_xml_gateway_query'] = array(
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Unique identifier.',
      ),
      'uid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'User ID of user that ran a query.',
      ),
      'query_timestamp' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Timestamp of when the query was run.',
      ),
      'service_name' => array(
        'type' => 'text',
        'length' => '1024',
        'not null' => TRUE,
        'description' => 'Name of the service at Companies House that was queried.',
      ),
      'params_json' => array(
        'type' => 'text',
        'size' => 'medium',
        'description' => 'JSON obj of the service parameters that were used.',
      ),
      'errors_json' => array(
        'type' => 'text',
        'size' => 'medium',
        'description' => 'JSON obj of any errors that were reported by the gateway.',
      ),
      'response_json' => array(
        'type' => 'text',
        'size' => 'medium',
        'description' => 'JSON obj of any non-error gateway response.',
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array(
      'uid' => array('uid'),
    ),
  );

  return $schema;
}
